//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CozaStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Commentid { get; set; }
        public Nullable<int> Userid { get; set; }
        public Nullable<int> Productid { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
